src/a/a/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import basefun
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('accounts',include('accounts.urls',namespace='')),
    path('accounts', include('django.contrib.auth.urls')),
    path('predict/', include('predict.urls',namespace='prd')),
    path('',basefun,name='c2'),

]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/a/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from a.views import basefun
app_name='accounts'
urlpatterns=[
   path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
   path('logout/', auth_views.LogoutView.as_view(), name='logout'),
   path('signup/', views.register,name='signup'),
   path('accounts/profile',basefun,name='c2'),
]

src/a/predict/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='predict'
urlpatterns=[

   path('',views.pred,name='prediction'),
   path('graphs',views.graph,name='graphs'),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/a/accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User,auth.models.PermissionsMixin):

    def __str__(self):
        return self.username

src/a/insert_data/models.py
from django.db import models

# Create your models here.
class Data(models.Model):
    title=models.CharField(max_length=256,null=True)
    Location1_name=models.CharField(max_length=256,null=True)
    Location2_name=models.CharField(max_length=256,null=True)
    Location3_name=models.CharField(max_length=256,null=True)
    Location4_name=models.CharField(max_length=256,null=True)

    file1=models.FileField(null=True,blank=True)
    file2=models.FileField(null=True,blank=True)
    description=models.TextField(null=True,blank=True)
    created=models.DateTimeField(auto_now_add=True,null=True)
    updated=models.DateTimeField(auto_now=True,null=True)
    class Meta:
        ordering=['title']

    def __str__(self):
        return self.title

src/a/predict/models.py
from django.db import models

# Create your models here.

src/a/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    email=forms.EmailField(required=True)#to customize as we want email to be there
    class Meta:
        model=User
        fields=[
        'username',
        'first_name',
        'last_name',
        'email',
        'password1',
        'password2'
        ]
    def save(self,commit=True):
        #commit true means data is now ready to be saved and stored
        user=super(UserCreateForm,self).save(commit=False)
        user.first_name=self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.email=self.cleaned_data['email']
        if  commit:
            user.save()
        return user

src/a/a/views.py
from django.shortcuts import render


def basefun(request):

    return render(request,"index.html",{})

src/a/accounts/views.py
from django.shortcuts import render,redirect,HttpResponse
from . import forms
from  django.contrib import messages
#create your views here

def register(request):
    if request.method=="POST":
        form=forms.UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Welcome to Traffic_prediction ...You are successfully registered!!')
            return redirect('login')

    else:
        #for the first time
        form=forms.UserCreateForm()
        context={"form":form}
        return render(request,"accounts/signup.html",context)

src/a/insert_data/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from .models import Data
from django.contrib import messages
from django.conf import settings
from . import forms
# Create your views here.

def comicsfun(request):
    comics_page=Comics.objects.all()
    paginator=Paginator(comics_page,9)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products = paginator.page(page)
    except(InvalidPage,EmptyPage):
        products=paginator.page(paginator.num_pages)


    return render(request,"comics/comics.html",{"products":products})
def comicsfun2(request,c_slug):
    try:
        products=get_object_or_404(Comics,slug=c_slug)
    except Exception as e:
        raise e
    return render(request,"comics/comics2.html",{"products":products})


# def pay(request):
#     return render(request,"comics/payment.html",{})

src/a/predict/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from insert_data.models import Data
from django.contrib import messages
from django.conf import settings
from . import views
from . import hackathon

# Create your views here.

def pred(request):
    detail=Data.objects.all()

    f=hackathon.fun()
    fit_data=f[0]
    pred_data=f[1]
    return render(request,"predict/predict.html",{"detail":detail,"fit_data":fit_data,"pred_data":pred_data})

def graph(request):
    f1=hackathon.fun()
    g=f1[2]
    return render(request,"predict/prediction2.html",{"g":g})

src/a/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
{% load staticfiles %}
<style type="text/css">
.form-group{
	width:450px;
	padding:20px;
	margin:20px auto ;
	background: white;
	border-radius: 10px;
	-webkit-border-radius:10px;
	-moz-border-radius: 10px;
  font-size:20px;
	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
	-moz-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
	-webkit-box-shadow: 0px 0px 90px rgba(0, 0, 0, 0.13);
}

.form-group .form-text .text-muted{
display:none;
}
.form-style-10 h1{

  background:rgb(44, 62, 80);
	padding: 20px 30px 15px 30px;
	margin: -30px -30px 30px -30px;
	border-radius: 10px 10px 0 0;
	-webkit-border-radius: 10px 10px 0 0;
	-moz-border-radius: 10px 10px 0 0;
	color: #fff;
	text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.12);
	font: normal 30px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";

	border: 1px solid #257C9E;
}
.form-style-10 h1 > span{
	display: block;
	margin-top: 2px;
	font: 13px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
}
.form-style-10 label{
	display: block;
	font: 13px Arial, Helvetica, sans-serif;
	color: #888;
	margin-bottom: 15px;
}

</style>
<div class="" style="text-align:center;background-color:white;border:1px solid white ";>
  <div class="container" style="text-align:center;padding:100px;margin-bottom:10px;margin-top:10px;height:auto;background-color:white );" >

  <h1 style="text-align:center;text-decoration:underline">LogIn</h1>
  <form  method="POST" >
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-default" value="Login">
  <a href="{% url 'accounts:signup' %}">Register</a>
  </form>

  </div>

</div>

{% endblock %}

src/a/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
{% load staticfiles %}
<style type="text/css">
.form-group{
	width:450px;
	padding:20px;
	margin:20px auto ;
	background: white;
	border-radius: 10px;
	-webkit-border-radius:10px;
	-moz-border-radius: 10px;
  font-size:20px;
	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
	-moz-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
	-webkit-box-shadow: 0px 0px 90px rgba(0, 0, 0, 0.13);
}

.form-group .form-text .text-muted{
display:none;
}
.form-style-10 h1{

  background:rgb(44, 62, 80);
	padding: 20px 30px 15px 30px;
	margin: -30px -30px 30px -30px;
	border-radius: 10px 10px 0 0;
	-webkit-border-radius: 10px 10px 0 0;
	-moz-border-radius: 10px 10px 0 0;
	color: #fff;
	text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.12);
	font: normal 30px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";

	border: 1px solid #257C9E;
}
.form-style-10 h1 > span{
	display: block;
	margin-top: 2px;
	font: 13px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
}
.form-style-10 label{
	display: block;
	font: 13px Arial, Helvetica, sans-serif;
	color: #888;
	margin-bottom: 15px;
}

</style>
<div class="" style="background-color:white;border:1px solid white ";>
  <div class="container" style="text-align:center;margin-bottom:10px;margin-top:10px;height:auto;background-color:white;" >

  <h1 style="text-align:center;text-decoration:underline">SignUp</h1>
  <form  method="POST" >
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-default" value="SignUp">

  </form>

  </div>

</div>

{% endblock %}

src/a/predict/templates/predict/predict.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
{% load staticfiles %}
<style type="text/css">
.form-group{
	width:450px;
	padding:20px;
	margin:20px auto ;
	background: white;
	border-radius: 10px;
	-webkit-border-radius:10px;
	-moz-border-radius: 10px;
  font-size:20px;
	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
	-moz-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
	-webkit-box-shadow: 0px 0px 90px rgba(0, 0, 0, 0.13);
}

.form-group .form-text .text-muted{
display:none;
}
.form-style-10 h1{

  background:rgb(44, 62, 80);
	padding: 20px 30px 15px 30px;
	margin: -30px -30px 30px -30px;
	border-radius: 10px 10px 0 0;
	-webkit-border-radius: 10px 10px 0 0;
	-moz-border-radius: 10px 10px 0 0;
	color: #fff;
	text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.12);
	font: normal 30px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";

	border: 1px solid #257C9E;
}
.form-style-10 h1 > span{
	display: block;
	margin-top: 2px;
	font: 13px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
}
.form-style-10 label{
	display: block;
	font: 13px Arial, Helvetica, sans-serif;
	color: #888;
	margin-bottom: 15px;
}

</style>
<div class="" style="background-color:white;border:1px solid white ";>
  <div class="container" style="text-align:center;margin-bottom:10px;margin-top:10px;height:auto;background-color:white;" >


		<div style="width:100%;">

			<div class="grid-container"  >

			{% for i in detail %}


			<div class="grid-item col-sm-4 col-lg-4" style="float:left;margin-left:75px;width:90%;height:420px;border:3px solid rgb(17, 122, 101 );color:black;">
			 	 <p><span style="padding:30px;"><b>Area name:</b></span><b style="font:40px;color:rgb(17, 122, 101 )">{{i.title}}</b></p>

			<p style="color:black;text-decoration:none;"><span style="padding:30px;"><b>Location1:</b></span>{{ i.Location1_name }}</p>
			<p style="color:black;text-decoration:none;"><span style="padding:30px;"><b>Location2:</b></span>{{ i.Location2_name }}</p>
			<p style="color:black;text-decoration:none;"><span style="padding:30px;"><b>Location3:</b></span>{{ i.Location3_name }}</p>
				<p style="color:black;text-decoration:none;"><span style="padding:30px;"><b>Location4:</b></span>{{ i.Location4_name }}</p>
			<p style="color:black;text-decoration:none;"><span style="padding:30px;">Created_time:</span>{{ i.created }}</p>
			<p style="font:-5px;color:black;text-decoration:none;">Updated_time:{{ i.updated }}</p>
		<a href="{% url 'predict:graphs' %}"><button type="button"  style="font-size:20px;" name="button">Click To View</button></a>
			</div>

			{% endfor %}
			</div>
			{% block content1 %}

			{% endblock %}
<br>
<br>
<br>
  </div>



</div>

<br>
<br><br>
{% endblock %}

src/a/predict/templates/predict/prediction2.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
{% load staticfiles %}
<style type="text/css">
.form-group{
	width:450px;
	padding:20px;
	margin:20px auto ;
	background: white;
	border-radius: 10px;
	-webkit-border-radius:10px;
	-moz-border-radius: 10px;
  font-size:20px;
	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
	-moz-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);
	-webkit-box-shadow: 0px 0px 90px rgba(0, 0, 0, 0.13);
}

.form-group .form-text .text-muted{
display:none;
}
.form-style-10 h1{

  background:rgb(44, 62, 80);
	padding: 20px 30px 15px 30px;
	margin: -30px -30px 30px -30px;
	border-radius: 10px 10px 0 0;
	-webkit-border-radius: 10px 10px 0 0;
	-moz-border-radius: 10px 10px 0 0;
	color: #fff;
	text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.12);
	font: normal 30px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";

	border: 1px solid #257C9E;
}
.form-style-10 h1 > span{
	display: block;
	margin-top: 2px;
	font: 13px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
}
.form-style-10 label{
	display: block;
	font: 13px Arial, Helvetica, sans-serif;
	color: #888;
	margin-bottom: 15px;
}

</style>
<div class="" style="background-color:white;border:1px solid white ";>
  <div class="container" style="text-align:center;background-color:white;" >

 <h1>GRAPHS</h1>
 <h2>RMS value: {{ g }}</h2>
<h3>This value is low that signifies that our model is accurate </h3>
<h3 style="margin-right:30px;">Junction 1</h3><img style="float:left;margin-top:-10px;width:50%;height:50%;" src="{% static "images/plot1.png" %}" alt="Plot1">
<h3>Junction 2</h3><img style="float:left;margin-top:-10px;width:50%;height:50%;" src="{% static "images/plot2.png" %}" alt="Plot1">
<h3>Junction 3</h3><img style="float:left;width:50%;height:50%;" src="{% static "images/plot3.png" %}" alt="Plot3">
<h3>Junction 4</h3><img style="float:left;width:50%;height:50%;" src="{% static "images/plot4.png" %}" alt="Plot4">
<h3>Junction 5</h3><img style="width:50%;height:50%;" src="{% static "images/plot5.png" %}" alt="Plot5">
<!--<h3>Junction 6</h3><img style="float:left;width:50%;height:50%;" src="{% static "images/plot6.png" %}" alt="Plot6">-->
<!--<h3>Junction 7</h3><img style="width:50%;height:50%;" src="{% static "images/plot7.png" %}" alt="Plot7">-->
<br>

{% endblock %}

src/a/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap4 %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/b1.css" %}">

    <link rel="stylesheet" href="{% static "css/comics.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Cinzel" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet">
      <link rel="stylesheet" href="https://cdn.rawgit.com/balzss/luxbar/ae5835e2/build/luxbar.min.css">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->

    <link rel="icon" type="image/jpg" href="https://previews.123rf.com/images/maxborovkov/maxborovkov1007/maxborovkov100700260/7338369-illustration-of-3d-t-symbol-.jpg">

    <title>TRAFFIC_PREDICTION</title>
    <style media="screen">

    .fa {
padding: 20px;
font-size: 30px;
width: 50px;
text-align: center;
text-decoration: none;
}

/* Add a hover effect if you want */
.fa:hover {
opacity: 0.7;
}

/* Set a specific color for each brand */

/* Facebook */
.fa-facebook {

color: white;
}

/* Twitter */
.fa-twitter {

color: white;
}
.fa-pinterest{
  color:white;
}
    </style>


    <style >
   #color{
     background-color:#b71c1c;
   }

      @import url(http://weloveiconfonts.com/api/?family=entypo);
      #wrapper{
      margin-top: 30px;

      }
      .box1{

        border-radius: 50px;
        font-family: 'entypo', sans-serif;
        border-radius: 100px;
        color:rgb(208, 211, 212);
        margin:20px;
        font-size: 25px;
        display: inline;
        cursor:pointer;
      }
    </style>
  </head>
  <body>
    <header id="luxbar" class="luxbar-fixed"  >
    <input type="checkbox" class="luxbar-checkbox" id="luxbar-checkbox"/>
    <div class="luxbar-menu luxbar-menu-right luxbar-menu-material-cyan">
        <ul class="luxbar-navigation">

            <li class="luxbar-header">
                <a href="/" class="luxbar-brand" style="font-size:40px;">TRAFFIC_PREDICTION</a>
                <label class="luxbar-hamburger luxbar-hamburger-doublespin"
                id="luxbar-hamburger" for="luxbar-checkbox"> <span></span> </label>
            </li>
            <li class="luxbar-item" style="font-size:26px;"><a href="/#about">About</a></li>
            <!-- <li class="luxbar-item" style="font-size:26px;"><a href="/#character">Characters</a></li> -->
            <li class="luxbar-item" style="font-size:26px;"><a href="{% url 'prd:prediction' %}"> Analyse</a></li>
            <li class="luxbar-item" style="font-size:26px;"><a href="{% url 'accounts:signup' %}">SignUp</a></li>

            {% if user.is_authenticated %}
                       <li class="luxbar-item" style="font-size:26px;"><a style="text-decoration:none;color:white;"  href="{% url 'accounts:logout' %}">LogOut</a></li>
                       {% else %}
                       <li class="luxbar-item" style="font-size:26px;"><a href="{% url 'accounts:login' %}">LogIn</a></li>
           {%endif%}



        </ul>
    </div>
</header>
<br><br>
<br>
<br>
<br>
{% if messages %}

    {% for msg in messages %}

      </script>
        <div class="alert alert-{{msg.level_tag}} text-center " style="margin-left:20%;margin-right:20%;" role="alert">
        {{msg.message}}
        </div>

    {% endfor %}


{% endif %}


{% block content %}
{% endblock %}
<br>

<footer style="font-size:20px;text-align: center;font-family:'Cinzel', serif;color:white;background-color:#0E6655 ;line-height:100px;">
<span style="padding:-100px;color:white;"><span style="margin-top:-10px;">KEEP IN TOUCH<br>
  <a href="https://www.facebook.com/TRFP-112150373595846/" class="fa fa-facebook"></a> &nbsp&nbsp
  <a href="https://twitter.com/Vartika60998058/" class="fa fa-twitter"></a> &nbsp&nbsp
  <a href="https://www.pinterest.com/marvelpedia20" class="fa fa-pinterest"></a> &nbsp&nbsp
<br>
</span>

Contact no- 8840084648 ,8890989098
</span> <br>



</footer>

<script>
var slideIndex = 0;
showSlides();

function showSlides() {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  slideIndex++;
  if (slideIndex > slides.length) {slideIndex = 1}
  slides[slideIndex-1].style.display = "block";
  setTimeout(showSlides, 2000); // Change image every 2 seconds
}
</script>
  </body>
</html>

src/a/templates/index.html
{% extends "base.html" %}
{% block content %}
<style>
  .alert .alert-success .text-center{
  	background-color:green;
  }


  #box11{
             height: 100vh;
             width: 100%;
             background-image: url("https://images.unsplash.com/photo-1564906158598-041131af6a04?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80");
             background-size: cover;
             display: table;
             background-attachment: fixed;
             opacity:0.9;
         }
         #box2{
             height: 100vh;
             width: 100%;
             background-image: url("https://wallpapercave.com/wp/wp2347565.jpg");
             background-size: cover;
             display: table;
             background-attachment: fixed;
             opacity:0.8;
         }
         #box3{
             height: 100vh;
             width: 100%;
             background-image: url("https://previews.123rf.com/images/peshkova/peshkova1802/peshkova180201083/95656566-creative-colorful-digital-business-chart-wallpaper-investment-and-finance-concept-3d-rendering.jpg");
             background-size: cover;
             display: table;
             background-attachment: fixed;
             opacity:0.9;
         }


        p{
             font-family: arial black;
            font-size: 50px;
            color:white;
            margin: 0px;
            margin-top:40px;
            vertical-align: middle;
            text-align: center;
            display: table-row;
            }

</style>
<div class="" style="margin-left:20px;margin-right:20px;">

  <div id="box11">
              <!-- <h1><a style="color:white;text-decoration:none;" href=""> </a></h1> -->

  </div>
          <div id="box2">
              <h1 ></h1>
              <p><a  href="{% url 'admin:index' %}" style="color:white;text-decoration:none;"> INSERT DATASETS INTO SYSTEM </a></p>
  </div>
           <div id="box3">
             <h1></h1>
              <p><a style="color:white;text-decoration:none;" href="{% url 'prd:prediction' %}">ANALYSE ROAD TRAFFIC</a></p>
          </div>

  <br><br>
  <!-- <div class="mySlides " style="height:600px;">

    <img height="100%" src="http://hdqwalls.com/wallpapers/avengers-infinity-war-2018-poster-4k-rq.jpg" style="width:100%">

  </div>

  <div class="mySlides" style="height:600px;">

    <img height="100%" src="https://pixelz.cc/wp-content/uploads/2017/01/marvel-avengers-age-of-ultron-uhd-4k-wallpaper.jpg" style="width:100%">

  </div>

  <div class="mySlides" style="height:600px;">

    <img  height="100%" src="https://atgbcentral.com/data/out/51/4349574-iron-man-h-d-wallpaper.jpg" style="width:100%">

  </div> -->

</div>
<br>
<br>
<div id="about" style="margin-left:10%;margin-right:10%;text-align:center;font-size:40px;font-family:'Cinzel', serif;">
<div >
About
</div>
<div class="" style="border-bottom:3px solid rgb(86, 101, 115); height:4%;width:50%;margin-left:25%;"></div>
<br>
<div class="" style="font-size:26px;font-family:'EB Garamond', serif;">
  Tired of waiting in traffic!! Use <b>TRAFFIC_PREDICTION</b> and get rid of it.
 It aims at solving traffic problems. Based on ML it targets at helping you find the best route so that you can avoid traffic while reaching your destination.
</div>
<br>
<iframe width="560" height="315" src="https://www.youtube.com/embed/USFdMIEhzZo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<br>
<br><br>




{% endblock %}